import streamlit as st
st.title("Band theory simulator")
st.write("Note: All units are currently arbitrary")
st.write("Move the sliders to view how various parameters affect electronic structure and conductivity")
a = st.slider("Unit cell width, a",  1.0, 10.0, 5.0, 0.1)
b = st.slider("Potential barrier width, b", 0.1, 5.0, 1.0, 0.1)
V0 = st.slider("Potential barrier height (V0)", 0.1, 20.0, 5.0, 0.1)
n = st.slider("Free electron per unit volume n", 1.0, 100.0, 50.0)
T = st.slider("Temperature in Kelvin", 1.0, 1000.0, 300.0)
st.header("Current values")
st.write(f"Unit cell width a = {a}")
st.write(f"Potential barrier width b = {b}")
st.write(f"Potential barrier height V0 = {V0}")
st.write(f"Free electron per unit volume = {n}")
st.write(f"Temperature in Kelvin T = {T}")
